server:
  port: 8080

spring:
  application:
    name: chronos-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: scheduler
              uri: ${SCHEDULER_URI:http://localhost:8081}
              predicates:
                - Path=/scheduler/**
              filters:
                - StripPrefix=1

            - id: worker
              uri: ${WORKER_URI:http://localhost:8083}
              predicates:
                - Path=/worker/**
              filters:
                - StripPrefix=1

      # CORS Configuration
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          "[/**]":
            # UPDATED: Reads env var 'FRONTEND_URI'.
            # If missing (local dev), defaults to http://localhost:8085
            allowed-origins: "${FRONTEND_URI:http://localhost:8085}"
            allowed-headers: "*"
            allowed-methods: "*"
            allow-credentials: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"