spring.application.name=Chronos_Worker
server.port=8081

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/chronos_db
spring.datasource.username=chronos
spring.datasource.password=chronos123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#replace legaccy timezone
spring.jackson.time-zone=Asia/Kolkata
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
# Logging Configuration
logging.level.org.springframework=INFO
logging.level.com.chronos=DEBUG

management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoints.web.base-path=/actuator

# Allow unauthenticated access
management.endpoint.prometheus.enabled=true
management.endpoint.health.probes.enabled=true
management.endpoint.health.show-details=always

# disable security for actuator
management.endpoints.web.exposure.include=*
spring.security.user.name=disabled
spring.security.user.password=disabled
management.endpoint.metrics.enabled=true
management.server.port=8083
